language: node_js
node_js:
  - "10.8.0"

install:
  - npm i -g yarn && yarn

before_script:
  - yarn prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: develop